"""empty message

Revision ID: 7b5263704887
Revises: 
Create Date: 2023-09-23 11:49:29.082746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5263704887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.String(length=280), nullable=False),
    sa.Column('course_type', sa.String(length=280), nullable=False),
    sa.Column('course_description', sa.String(length=280), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('quizzes', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('lms_permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=280), nullable=False),
    sa.Column('permission_module', sa.String(length=280), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_module')
    )
    op.create_table('lms_quizzes',
    sa.Column('quiz_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_name', sa.String(length=280), nullable=False),
    sa.Column('quiz_type', sa.String(length=280), nullable=False),
    sa.PrimaryKeyConstraint('quiz_id'),
    sa.UniqueConstraint('quiz_name')
    )
    op.create_table('lms_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gut_health', sa.String(length=280), nullable=False),
    sa.Column('hormones', sa.String(length=280), nullable=False),
    sa.Column('weight_loss', sa.String(length=280), nullable=False),
    sa.Column('mommy_makeover', sa.String(length=280), nullable=False),
    sa.Column('vegan', sa.String(length=280), nullable=False),
    sa.Column('keto', sa.String(length=280), nullable=False),
    sa.Column('pescatarian', sa.String(length=280), nullable=False),
    sa.Column('vegetarian', sa.String(length=280), nullable=False),
    sa.Column('intermittent_fasting', sa.String(length=280), nullable=False),
    sa.Column('nutrition', sa.String(length=280), nullable=False),
    sa.Column('cardio', sa.String(length=280), nullable=False),
    sa.Column('habits_motivation', sa.String(length=280), nullable=False),
    sa.Column('neuroscience_food', sa.String(length=280), nullable=False),
    sa.Column('loa_manifesting', sa.String(length=280), nullable=False),
    sa.Column('selfcare_sleep_stress', sa.String(length=280), nullable=False),
    sa.Column('vagus_nerve', sa.String(length=280), nullable=False),
    sa.Column('meditation', sa.String(length=280), nullable=False),
    sa.Column('yoga', sa.String(length=280), nullable=False),
    sa.Column('pilates', sa.String(length=280), nullable=False),
    sa.Column('nature', sa.String(length=280), nullable=False),
    sa.Column('weight_lifting', sa.String(length=280), nullable=False),
    sa.Column('hiits', sa.String(length=280), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_chatgpt_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('podcast_transcripts', sa.String(length=280), nullable=False),
    sa.Column('youtube_transcripts', sa.String(length=280), nullable=False),
    sa.Column('health_blogs', sa.String(length=280), nullable=False),
    sa.Column('health_wikis', sa.String(length=280), nullable=False),
    sa.Column('health_book_libraries', sa.String(length=280), nullable=False),
    sa.Column('health_web_scrapes', sa.String(length=280), nullable=False),
    sa.Column('recipes', sa.String(length=280), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.course_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_chatgpt_sources_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['lms_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_courses_permissions',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.course_id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['lms_permissions.permission_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'permission_id')
    )
    op.create_table('lms_courses_quizzes',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['lms_permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['lms_quizzes.quiz_id'], ),
    sa.PrimaryKeyConstraint('permission_id', 'quiz_id')
    )
    op.create_table('lms_logins',
    sa.Column('login_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=280), nullable=False),
    sa.Column('password', sa.String(length=280), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['lms_permissions.permission_id'], ),
    sa.PrimaryKeyConstraint('login_id')
    )
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('googleid', sa.String(length=128), nullable=True),
    sa.Column('gwttoken', sa.String(length=128), nullable=True),
    sa.Column('profile_active', sa.Boolean(), nullable=True),
    sa.Column('calculated_cal_goal', sa.Integer(), nullable=True),
    sa.Column('starting_weight', sa.Integer(), nullable=True),
    sa.Column('avatar_photo', sa.JSON(), nullable=True),
    sa.Column('target_weight', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['lms_logins.login_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('googleid'),
    sa.UniqueConstraint('gwttoken'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_users')
    op.drop_table('lms_logins')
    op.drop_table('lms_courses_quizzes')
    op.drop_table('lms_courses_permissions')
    op.drop_table('lms_chatgpt_sources_topics')
    op.drop_table('lms_chatgpt_sources')
    op.drop_table('lms_topics')
    op.drop_table('lms_quizzes')
    op.drop_table('lms_permissions')
    op.drop_table('lms_courses')
    # ### end Alembic commands ###
